name: Cardapio digital - Gerar versão

on:
  workflow_dispatch: # Roda apenas manualmente pelo painel do GitHub
    inputs:
      #version:
      #  description: 'Versão do build'
      #  required: true
      #  default: '1.0.0'
      android:
        description: "Gerar versão Android?"
        default: true
        type: boolean
      email:
        description: "Deseja enviar email ao finalizar?"
        default: false
        type: boolean

env:
  VERSION: ${{vars.VERSAO}}
  BUILD: ${{vars.build}}
  SENHA_CERTIFICADO_CLOUDFY: ${{ secrets.SENHA_CERTIFICADO_CLOUDFY }}
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_KEY }}
  SIGNATURE_APP_ID: ${{ secrets.SIGNATURE_APP_ID }}
  SIGNATURE_CERTIFICATE_NAME: ${{ secrets.SIGNATURE_CERTIFICATE_NAME }}
  SIGNATURE_VAULT_ID: ${{ secrets.SIGNATURE_VAULT_ID }}
  SIGNATURE_PASSWORD: ${{ secrets.SIGNATURE_PASSWORD }}
  SIGNATURE_TENANT_ID: ${{ secrets.SIGNATURE_TENANT_ID }}

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./flutter/cardapio

    steps:
      - name: Gerar Variáveis de Ambiente
        working-directory: .
        id: compute
        run: |
          echo 'DeployName=prod' >> $GITHUB_ENV
          echo 'DeployNameUpperCase=Cardapio' >> $GITHUB_ENV
          echo 'UrlId=6' >> $GITHUB_ENV
          VARIABLE=${{ github.event.inputs.android }}

          # Converte string para 0/1
          if [ "$VARIABLE" = "true" ]; then VARIABLE_BOOL=1; else VARIABLE_BOOL=0; fi          


          # OR lógico
          if [ $((VARIABLE_BOOL)) -eq 1 ]; then
            EXECUTE=true
          else
            EXECUTE=false
          fi

          echo "Valor do execute: $EXECUTE"

          echo "execute=$EXECUTE" >> $GITHUB_OUTPUT
      # Clonar o repositório principal do Flutter
      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        with:
          repository: cloudfysystems/FLUTTER
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutter

      # Clonar o repositório de versão
      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        with:
          path: version-repo

      # Ler e atualizar a versão
      - name: Ler versão atual
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        working-directory: version-repo
        shell: bash
        run: |
          VERSION_FILE="version${{env.DeployNameUpperCase}}.json"

          # Atualiza o JSON corretamente
          jq '.speedy.build += 1 | .speedy.version += 1 | .speedy.patch = 0' "$VERSION_FILE" > tmp.json

          mv tmp.json "$VERSION_FILE"

          # Pega os valores após a atualização
          BUILD=$(jq -r '.speedy.build' "$VERSION_FILE")
          VERSION=$(jq -r '.speedy.version' "$VERSION_FILE")
          SIMPLE=$(jq -r '.speedy.simple' "$VERSION_FILE")

          echo "Versao Build: $BUILD"
          echo "Versao Version: $VERSION"
          echo "Versao Gerada: $SIMPLE.$VERSION.0"

          echo "VERSAO=$SIMPLE.$VERSION.0" >> $GITHUB_ENV
          echo "VERSAO_BUILD=$BUILD" >> $GITHUB_ENV

          echo "Novo JSON:"
          cat "$VERSION_FILE"

      # Criar arquivo .jks a partir de base64
      - name: Criar arquivo .jks
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        shell: bash
        run: |
          mkdir -p certificado
          echo "${{ secrets.KEYSTORE_ADM }}" | base64 -d > certificado/certificado-keystore.keystore

      # Setup Shorebird
      - name: 🐦 Setup Shorebird
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      # Criar arquivo key.properties
      - name: Criar arquivo key.properties
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        shell: bash
        run: |
          echo "storePassword=${{ secrets.SENHA_KEYSTORE }}" > android/key.properties
          echo "keyPassword=${{ secrets.SENHA_KEYSTORE }}" >> android/key.properties
          echo "keyAlias=cloudcommerce" >> android/key.properties
          echo "storeFile=../../certificado/certificado-keystore.keystore" >> android/key.properties

      # Set Up Java (usando Oracle JDK 17)
      - name: Set Up Java
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      # Atualizar versão no arquivo Dart
      - name: Atualiza versão no pubspec.yaml
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        shell: bash
        run: |
          sed -i "s/^version:.*/version: $VERSAO+${{ env.VERSAO_BUILD }}/" pubspec.yaml
          cat pubspec.yaml

      # Executar build do Shorebird
      - name: 🚀 Shorebird Release
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        id: shorebird-release
        uses: shorebirdtech/shorebird-release@v1
        with:
          args: --target lib/main.dart --artifact apk
          platform: android
          flutter-version: ${{vars.FLUTTER_VERSION_SDK_ANDROID_SMART}}
          working-directory: ./flutter/cardapio

      - name: Renomear arquivos Android
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        working-directory: .
        run: |
          echo "Renomeando APK"
          if [ -f "flutter/cardapio/build/app/outputs/flutter-apk/app-release.apk" ]; then
            mv flutter/cardapio/build/app/outputs/flutter-apk/app-release.apk flutter/cardapio/build/app/outputs/flutter-apk/CloudfyCardapioAndroid.apk
            echo "APK renomeado para CloudfyCardapioAndroid.apk"
          else
            echo "⚠️ APK não encontrado!"
          fi

          echo "Renomeando AAB"
          if [ -f "flutter/cardapio/build/app/outputs/bundle/release/app-release.aab" ]; then
            mv flutter/cardapio/build/app/outputs/bundle/release/app-release.aab flutter/cardapio/build/app/outputs/bundle/release/CloudfyCardapioAndroid.aab
            echo "AAB renomeado para CloudfyCardapioAndroid.aab"
          else
            echo "⚠️ AAB não encontrado!"
          fi

      - name: Criando o release
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSAO }}_cardapio${{env.DeployNameUpperCase}}
          name: v${{ env.VERSAO }}_cardapio${{env.DeployNameUpperCase}}
          files: |
            flutter/cardapio/build/app/outputs/flutter-apk/CloudfyCardapioAndroid.apk
            flutter/cardapio/build/app/outputs/bundle/release/CloudfyCardapioAndroid.aab
          body: Release gerado automaticamente.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Chamar API de alteração de dados android
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        run: |
          URLANDROID="https://github.com/cloudfysystems/Version/releases/download/v${{ env.VERSAO }}_cardapio${{env.DeployNameUpperCase}}/CloudfyCardapioAndroid.apk"
          echo "$URLANDROID"
          echo "Chamando API de validação..."

          JSON_DATA=$(cat <<EOF
          {
            "JSON": true,
            "Parameters": {
              "Versao": "${{ env.VERSAO }}",
              "PSW": "${{ secrets.SENHA_API_ALTERAR_URL }}",
              "URL": "$URLANDROID",
              "NR_ID": ${{ env.UrlId }}
            }
          }
          EOF
          )

          echo $JSON_DATA

          response=$(curl -s -o response.txt -w "%{http_code}" \
            -X POST https://api.cloudfy.net.br/H02SF0107A \
            -H "Content-Type: application/json" \
            -d "$JSON_DATA")

          echo "Código HTTP: $response"
          cat response.txt

          if [ "$response" != "200" ]; then
            echo "❌ Falha na chamada da API. Abortando workflow."
            exit 1
          fi

      - name: Atualizar branch com merge (se necessário)
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        working-directory: version-repo
        run: |
          git config user.name "cloudfysystems"
          git config user.email "cloudfysystems@gmail.com"

          # Garante que estamos na branch correta
          git branch --show-current

          # Tenta fazer pull e merge automático
          git pull origin HEAD --no-rebase || true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit das alterações
        uses: EndBug/add-and-commit@v9
        if: ${{ (steps.compute.outputs.execute == 'true') }}
        with:
          author_name: cloudfysystems
          author_email: cloudfysystems@gmail.com
          message: "alterada versão do build ${{env.DeployNameUpperCase}}"
          cwd: ./version-repo
          add: "version${{env.DeployNameUpperCase}}.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  #Job que vai atualizar o git, sincronizar os fontes
  FinishJob:
    needs: [android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./flutterrepo

    steps:
      - name: Calculando a combinação dos booleans Android
        id: compute
        working-directory: .
        run: |
          ANDROID=${{ github.event.inputs.android }}          



          # Converte string para 0/1
          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi          


          # OR lógico
          if [ $((ANDROID_BOOL | IOS_BOOL)) -eq 1 ]; then
            COMBINED=true
          else
            COMBINED=false
          fi

          echo "combined=$COMBINED" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          repository: cloudfysystems/FLUTTER
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: flutterrepo

      - uses: actions/checkout@v4
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        with:
          path: version-repo

      - name: Recuperando os commits entre produção e main
        id: log
        if: ${{ (steps.compute.outputs.combined == 'true') }}
        continue-on-error: true
        run: |
          git config --global user.name "cloudfysystems"
          git config --global user.email "cloudfysystem@gmail.com"
          git config --global pull.rebase false
          git pull origin production
          commits=$(git log origin/production..origin/main --pretty=format:"- %s (%an)<br>" --no-merges)
          {
            echo "commit_messages<<EOF"
            echo "$commits"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          git checkout production
          git merge origin/main --no-ff -m "gerando versao na falcatrua" --allow-unrelated-histories
          git push origin production

      - name: Envia e-mail com resumo
        uses: dawidd6/action-send-mail@v3
        #if: ${{ steps.compute.outputs.combined == 'true' && github.event.inputs.email}}
        if: false
        with:
          server_address: mail.cloudfy.net.br
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Cardapio digital - Gerado versão em produção"
          html_body: |
            <p><b>Olá time!</b></p>


            Foi gerada uma nova versão em produção do Cardapio Digital!<br><br>
              
            Commits incluídos:<br><br>
              
            <b>${{ steps.log.outputs.commit_messages }}</b><br><br>
              
            <p>Os novos arquivos estão disponíveis na área de download</p>
              
            <p><b>Menos foco, mais ansiedade!</b></p>
          to: ${{ vars.EMAIL }}
          from: Cloudfy Versão <noreply@cloudfy.net.br>
          secure: true
